import { createSlice, PayloadAction } from '@reduxjs/toolkit';

// Define the initial state for authentication
interface AuthState {
  token: string | null;
}

// Initial state
const initialState: AuthState = {

  token: "test",

};

// Create the authentication slice
const authSlice = createSlice({
  name: 'auth',
  initialState,
  reducers: {
    setCredentials: (state, action: PayloadAction<{ uid: string; token: string }>) => {

      state.token = action.payload.token;
    },

    logout: (state) => {
      state.token = null;
    },

    updateToken: (state, action: PayloadAction<string | null>) => {
      state.token = action.payload;
    },


  },
});

// Export the actions generated by createSlice
export const { setCredentials, logout, updateToken } = authSlice.actions;

// Export the reducer to be used in the store
export default authSlice.reducer;
